drop table if exists item CASCADE;
create table item
(
    id bigint generated by default as identity,
    name varchar(255),
    price integer not null,
    count integer not null,
    primary key (id)
);